--- #YAML:1.0
name:               Net-BGP
version:            0.14
abstract:           Object-oriented API to the BGP protocol
author:
    - Stephen J. Scheck <code@neurosphere.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::Util:     1.01
    Test::Harness:  2.00
    Test::More:     0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
